version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-b2202"
s3_bucket = "mhudn-izaan-cicd"
s3_prefix = "sam-app-b2202"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
