version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-demo"
s3_bucket = "sam-app-deploment-project"
s3_prefix = "sam-app-demo"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
